export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const IS_RECIPE_TITLE_DOUBLE = 'IS_RECIPE_TITLE_DOUBLE';
export const DOUBLE_RECIPE_TITLE_ERROR = 'DOUBLE_TITLE_ERROR';
export const IS_RECIPE_CREATING = 'IS_RECIPE_ADDING';
export const CREATE_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';
